---
title: "HW_5_B"
author: "Jered May"
date: "2024-11-17"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

#Load Data and Libraries 
```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(purrr)
library(broom)
library(ggplot2)
library(scales)
library(forcats)
library(lubridate)

homicides_url <- paste0("https://raw.githubusercontent.com/washingtonpost/",
                        "data-homicides/refs/heads/master/homicide-data.csv")

homicides <- read_csv(homicides_url) %>%
  unite(city_name, city, state, sep = ",", remove =FALSE)


homicides$reported_date <- as.Date(as.character(homicides$reported_date),
                                   format = "%Y%m%d")

# confirm reported_date is a Date class
print(class(homicides$reported_date))
```

# Debuging 
```{r}
# Debugging 
tulsa_records <- homicides %>%
  filter(city == "Tulsa",
         victim_last == "HARRIS")
print(tulsa_records, width = Inf)

# mutating the one record of Tulsa, AL
homicides <- read_csv(homicides_url) %>%
  mutate(state = if_else(city == "Tulsa", "OK", state)) %>%
  unite(city_name, city, state, sep =", ", remove = FALSE)

# Check to see that the single Tulsa, AL record is changed
tulsa_records <- homicides %>%
  filter(city == "Tulsa",
         victim_last == "HARRIS")
print(tulsa_records, width = Inf)

```

# Filter
```{r}
# filtering for Baltimore homicides with seasons
Baltimore_homicides <- homicides %>%
  filter(city_name == "Baltimore, MD") %>%
  mutate(
    reported_date = ymd(reported_date),
    year = year(reported_date),
    month = month(reported_date),
    season = case_when(
      month %in% c(05, 06, 07, 08, 09, 10) ~ "Summer",
      TRUE ~ "Winter"
    )
  )

#Counts
monthly_counts <- Baltimore_homicides %>%
  group_by(year, month, season) %>%
  nest() %>%
  mutate(
    count = map_int(data, nrow)
    ) %>%
  ungroup() %>%
  mutate(
    date = make_date(year, month, 1)
  ) %>%
  select(year, month, count, season, date)


print(monthly_counts)


```


#Graph
```{r fig.width=12,fig.height=3}
# Plot with ggplot2
ggplot(monthly_counts, aes(x = date, y = count, fill = season)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = c("Summer" = "gray", "Winter" = "lightblue")) +
  geom_vline(xintercept = as.Date("2015-04-01"), linetype = "longdash",
             color = "red", size = 1) +
  annotate("text", 
           x = as.Date("2015-04-12"), 
           y = max(monthly_counts$count) - 19,  
           label = ("Arrest of\nFreddie Gray"), 
           color = "white", 
           hjust = 1.13,
           vjust = -1) +
   labs(
    x = "Date",
    y = "Monthly homicides",
    title = "Homicides in Baltimore, MD") +
  theme_dark() +
  scale_y_continuous(
    limits = c(0, max(monthly_counts$count))) +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(title = NULL)) +
  geom_smooth(aes(group = 1), method = "loess", color = "blue", span = 0.1,
              se = FALSE, show.legend =FALSE) 
  
```


